using System.Globalization;
using ClientAvalonia.Domain;
using ClientAvalonia.Rendering;
using ClientCore;
using ClientCore.Enums;
using ClientCore.Extensions;
using Rampastring.Tools;

namespace ClientAvalonia.Services;

/// <summary>Writes spawn.ini (and optionally spawnmap.ini) for campaign missions.</summary>
public static class CampaignSpawnWriter
{
    private static readonly string[] DifficultyIniPaths =
    [
        "INI/Map Code/Difficulty Easy.ini",
        "INI/Map Code/Difficulty Medium.ini",
        "INI/Map Code/Difficulty Hard.ini",
    ];

    public static void Write(MissionEntry mission, int difficultyIndex, UiNodeViewModel? overlayRoot = null)
    {
        difficultyIndex = Math.Clamp(difficultyIndex, 0, DifficultyIniPaths.Length - 1);

        FileInfo spawnerSettingsFile = SafePath.GetFile(ProgramConstants.GamePath, ProgramConstants.SPAWNER_SETTINGS);
        spawnerSettingsFile.Delete();

        bool copyMapsToSpawnmapIni = ClientConfiguration.Instance.CopyMissionsToSpawnmapINI;

        Logger.Log("CampaignSpawnWriter: writing spawn.ini");

        var spawnIni = new IniFile(spawnerSettingsFile.FullName) { Comment = "Generated by CnCNet Client" };
        var settings = new IniSection("Settings");

        if (copyMapsToSpawnmapIni)
            settings.AddKey("Scenario", ProgramConstants.SPAWNMAP_INI);
        else
            settings.AddKey("Scenario", mission.Scenario);

        int gameSpeed = UserINISettings.Instance.GameSpeed;
        if (gameSpeed == 0)
            UserINISettings.Instance.GameSpeed.Value = 1;

        settings.AddKey("CampaignID", mission.CampaignId.ToString(CultureInfo.InvariantCulture));
        settings.AddKey("GameSpeed", UserINISettings.Instance.GameSpeed.ToString());

        switch (ClientConfiguration.Instance.ClientGameType)
        {
            case ClientType.YR or ClientType.Ares:
                settings.AddKey("Ra2Mode", (!mission.RequiredAddon).ToString(CultureInfo.InvariantCulture));
                break;
            case ClientType.TS:
                settings.AddKey("Firestorm", mission.RequiredAddon.ToString(CultureInfo.InvariantCulture));
                break;
        }

        settings.AddKey("CustomLoadScreen", LoadingScreenController.GetLoadScreenName(mission.Side.ToString(CultureInfo.InvariantCulture)));
        settings.AddKey("IsSinglePlayer", "Yes");
        settings.AddKey("SidebarHack", ClientConfiguration.Instance.SidebarHack.ToString(CultureInfo.InvariantCulture));
        settings.AddKey("Side", mission.Side.ToString(CultureInfo.InvariantCulture));
        settings.AddKey("BuildOffAlly", mission.BuildOffAlly.ToString(CultureInfo.InvariantCulture));

        UserINISettings.Instance.Difficulty.Value = difficultyIndex;

        settings.AddKey("DifficultyModeHuman",
            mission.PlayerAlwaysOnNormalDifficulty ? "1" : difficultyIndex.ToString(CultureInfo.InvariantCulture));
        settings.AddKey("DifficultyModeComputer", GetComputerDifficulty(difficultyIndex).ToString(CultureInfo.InvariantCulture));

        spawnIni.AddSection(settings);
        SpawnIniApplier.ApplyLobbyControls(overlayRoot, spawnIni);
        ApplyCampaignForcedSpawnOptions(spawnIni);
        spawnIni.WriteIniFile();

        if (copyMapsToSpawnmapIni)
            WriteSpawnMap(mission, difficultyIndex);

        UserINISettings.Instance.SaveSettings();
    }

    private static void WriteSpawnMap(MissionEntry mission, int difficultyIndex)
    {
        string scenarioPath = SafePath.CombineFilePath(ProgramConstants.GamePath, mission.Scenario);
        if (!File.Exists(scenarioPath))
        {
            Logger.Log($"CampaignSpawnWriter: scenario file not found: {scenarioPath}");
            return;
        }

        var mapIni = new IniFile(scenarioPath);
        var difficultyIni = new IniFile(SafePath.CombineFilePath(ProgramConstants.GamePath, DifficultyIniPaths[difficultyIndex]));
        IniFile.ConsolidateIniFiles(mapIni, difficultyIni);

        mapIni.WriteIniFile(SafePath.CombineFilePath(ProgramConstants.GamePath, ProgramConstants.SPAWNMAP_INI));
    }

    private static int GetComputerDifficulty(int difficultyIndex) => Math.Abs(difficultyIndex - 2);

    private static void ApplyCampaignForcedSpawnOptions(IniFile spawnIni)
    {
        string gameOptionsPath = SafePath.CombineFilePath(ProgramConstants.GetBaseResourcePath(), ClientConfiguration.GAME_OPTIONS);
        if (!File.Exists(gameOptionsPath))
            return;

        var gameOptionsIni = new IniFile(gameOptionsPath);
        List<string>? forcedKeys = gameOptionsIni.GetSectionKeys("CampaignForcedSpawnIniOptions");
        if (forcedKeys == null)
            return;

        foreach (string key in forcedKeys)
        {
            spawnIni.SetStringValue("Settings", key,
                gameOptionsIni.GetStringValue("CampaignForcedSpawnIniOptions", key, string.Empty));
        }
    }
}
