using ClientAvalonia.CnCNet;
using ClientAvalonia.Configuration;
using ClientAvalonia.Domain;
using ClientAvalonia.GlobalState.Environment;
using ClientAvalonia.Rendering;
using ClientAvalonia.Session;
using ClientCore;
using Rampastring.Tools;
using ClientAvalonia.GlobalState;

namespace ClientAvalonia.Services;

/// <summary>Writes spawn.ini / spawnmap.ini for CnCNet (XNA GameLobbyBase.WriteSpawnIni + CnCNetGameLobby.WriteSpawnIniAdditions).</summary>
public static class CnCNetMultiplayerSpawnWriter
{
    /// <summary>
    /// Phase 3 P3-2：Session-aware 主入口——直接吃 <see cref="IReadOnlyList{IPlayerSlot}"/>（session.PlayerSlots），
    /// 不再依赖 <c>LobbyPlayerState</c>。当 <paramref name="roomPlayers"/> 非空时仍优先用 PO DTO
    /// （保留 NAT 端口等只在 DTO 里存在的字段）。
    /// </summary>
    public static void Write(
        MapEntry map,
        GameModeEntry gameMode,
        CnCNetStartGameInfo startInfo,
        IReadOnlyList<IPlayerSlot> slots,
        UiNodeViewModel? lobbyRoot,
        IReadOnlyList<CnCNetGameRoomPlayer>? roomPlayers,
        CnCNetGameOptionsState? options)
    {
        ArgumentNullException.ThrowIfNull(slots);

        int randomSeed = options?.RandomSeed ?? 0;
        if (randomSeed == 0)
            randomSeed = Random.Shared.Next();

        SkirmishSpawnWriter.WriteSpawnMap(map, gameMode, lobbyRoot);
        WriteSpawnIni(map, gameMode, startInfo, slots, lobbyRoot, roomPlayers, options, randomSeed);
    }

    private static void WriteSpawnIni(
        MapEntry map,
        GameModeEntry gameMode,
        CnCNetStartGameInfo startInfo,
        IReadOnlyList<IPlayerSlot> slots,
        UiNodeViewModel? lobbyRoot,
        IReadOnlyList<CnCNetGameRoomPlayer>? roomPlayers,
        CnCNetGameOptionsState? options,
        int randomSeed)
    {
        IGameEnvironment env = EnvironmentServices.Resolve<IGameEnvironment>();
        string playerName = env.PlayerName;
        string gamePath = env.GamePath;
        FileInfo spawnerSettingsFile = SafePath.GetFile(gamePath, ProgramConstants.SPAWNER_SETTINGS);
        spawnerSettingsFile.Delete();

        Logger.Log("Writing spawn.ini");

        var portsByName = new Dictionary<string, ushort>(StringComparer.OrdinalIgnoreCase);
        foreach (KeyValuePair<string, ushort> pair in startInfo.PlayerPorts)
        {
            if (CnCNetPortValidator.IsValid(pair.Value))
                portsByName[pair.Key] = pair.Value;
        }

        if (portsByName.Count == 0 && roomPlayers != null)
        {
            foreach (CnCNetGameRoomPlayer player in roomPlayers.Where(p => !p.IsAi))
            {
                if (CnCNetPortValidator.IsValid(player.Port))
                    portsByName[player.Name] = player.Port;
            }
        }

        List<LobbyPlayerSlot> humans = BuildHumans(slots, roomPlayers);
        List<LobbyPlayerSlot> ais = BuildAis(slots, roomPlayers);

        if (humans.Count == 0)
        {
            humans.Add(new LobbyPlayerSlot
            {
                Name = playerName,
                IsHumanLocal = true,
            });
        }

        if (ais.Count == 0)
        {
            ais.Add(new LobbyPlayerSlot
            {
                Name = env.AiPlayerNames.Count > 0 ? env.AiPlayerNames[0] : "Easy AI",
                IsAi = true,
                AiLevel = 0,
                SideIndex = 0,
                ColorIndex = 1,
            });
        }

        var allOccupied = new List<LobbyPlayerSlot>(humans.Count + ais.Count);
        allOccupied.AddRange(humans);
        allOccupied.AddRange(ais);

        IReadOnlyList<LobbyPlayerHouseResolver.ResolvedHouse> houses =
            LobbyPlayerHouseResolver.Resolve((IReadOnlyList<IPlayerSlot>)allOccupied, randomSeed);

        int localHumanIndex = humans.FindIndex(h => h.IsHumanLocal || h.Name == playerName);
        if (localHumanIndex < 0)
            localHumanIndex = 0;

        LobbyPlayerHouseResolver.ResolvedHouse localHouse = houses[localHumanIndex];
        ushort localPort = startInfo.LocalPlayerPort;

        var spawnIni = new IniFile(spawnerSettingsFile.FullName) { Comment = "Generated by CnCNet Client" };
        var settings = new IniSection("Settings");

        settings.SetStringValue("Name", playerName);
        settings.SetStringValue("Scenario", ProgramConstants.SPAWNMAP_INI);
        settings.SetStringValue("UIGameMode", gameMode.UntranslatedUIName);
        settings.SetStringValue("UIMapName", map.UntranslatedName);

        if (map.IsOfficial)
            settings.SetStringValue("MapID", map.BaseFilePath);

        settings.SetIntValue("PlayerCount", humans.Count);
        settings.SetIntValue("Side", localHouse.InternalSideIndex);
        settings.SetBooleanValue("IsSpectator", localHouse.IsSpectator);
        settings.SetIntValue("Color", localHouse.GameColorIndex);
        settings.SetStringValue("CustomLoadScreen", LoadingScreenController.GetLoadScreenName(localHouse.InternalSideIndex.ToString()));
        settings.SetIntValue("AIPlayers", ais.Count);
        settings.SetIntValue("Seed", randomSeed);

        if (GetHumanTeamCount(humans) > 1)
            settings.SetBooleanValue("CoachMode", true);

        spawnIni.AddSection(settings);

        // CnCNetGameLobby.WriteSpawnIniAdditions — immediately after Settings (XNA order).
        spawnIni.SetStringValue("Tunnel", "Ip", startInfo.Tunnel.Address);
        spawnIni.SetIntValue("Tunnel", "Port", startInfo.Tunnel.Port);
        spawnIni.SetIntValue("Settings", "GameID", startInfo.UniqueGameId);
        spawnIni.SetBooleanValue("Settings", "Host", startInfo.IsHost);
        spawnIni.SetIntValue("Settings", "Port", localPort);

        SpawnIniApplier.ApplyLobbyControls(lobbyRoot, spawnIni);
        ApplyForcedSpawnOptions(spawnIni);
        ForcedSpawnCatalog.ApplyGameModeForcedSpawn(spawnIni, gameMode);
        ForcedSpawnCatalog.ApplyMapForcedSpawn(spawnIni, map, humans.Count, ais.Count);

        // MultiplayerGameLobby.WriteSpawnIniAdditions
        IGameConfiguration config = EnvironmentServices.Resolve<IGameConfiguration>();
        int frameSendRate = options?.FrameSendRate ?? config.DefaultFrameSendRate;
        int maxAhead = options?.MaxAhead ?? config.DefaultMaxAhead;
        int protocol = options?.ProtocolVersion ?? config.DefaultProtocolVersion;
        spawnIni.SetIntValue("Settings", "FrameSendRate", frameSendRate);
        if (maxAhead > 0)
            spawnIni.SetIntValue("Settings", "MaxAhead", maxAhead);
        spawnIni.SetIntValue("Settings", "Protocol", protocol);
        spawnIni.SetBooleanValue("Settings", "SidebarHack", config.SidebarHack);

        List<int> multiCmbIndexes = BuildMultiComboIndexes(humans, houses);

        int otherId = 1;
        for (int humanIndex = 0; humanIndex < humans.Count; humanIndex++)
        {
            LobbyPlayerSlot human = humans[humanIndex];
            if (human.Name == playerName)
                continue;

            LobbyPlayerHouseResolver.ResolvedHouse house = houses[humanIndex];
            string sectionName = "Other" + otherId;
            spawnIni.SetStringValue(sectionName, "Name", human.Name);
            spawnIni.SetIntValue(sectionName, "Side", house.InternalSideIndex);
            spawnIni.SetBooleanValue(sectionName, "IsSpectator", house.IsSpectator);
            spawnIni.SetIntValue(sectionName, "Color", house.GameColorIndex);
            spawnIni.SetStringValue(sectionName, "Ip", "0.0.0.0");
            if (portsByName.TryGetValue(human.Name, out ushort remotePort))
                spawnIni.SetIntValue(sectionName, "Port", remotePort);

            otherId++;
        }

        if (ais.Count > 0)
        {
            for (int aiIndex = 0; aiIndex < ais.Count; aiIndex++)
            {
                int multiId = multiCmbIndexes.Count + aiIndex + 1;
                string keyName = "Multi" + multiId;
                LobbyPlayerHouseResolver.ResolvedHouse house = houses[humans.Count + aiIndex];
                spawnIni.SetIntValue("HouseHandicaps", keyName, LobbyPlayerHouseResolver.HouseHandicapFromAiLevel(ais[aiIndex].AiLevel));
                spawnIni.SetIntValue("HouseCountries", keyName, house.InternalSideIndex);
                spawnIni.SetIntValue("HouseColors", keyName, house.GameColorIndex);
            }
        }

        for (int multiIndex = 0; multiIndex < multiCmbIndexes.Count; multiIndex++)
        {
            int playerIndex = multiCmbIndexes[multiIndex];
            if (houses[playerIndex].IsSpectator)
                spawnIni.SetBooleanValue("IsSpectator", "Multi" + (multiIndex + 1), true);
        }

        var startingWaypoints = new List<int>(humans.Count);
        for (int i = 0; i < humans.Count; i++)
            startingWaypoints.Add(humans[i].StartIndex > 0 ? humans[i].StartIndex - 1 : -1);

        SpawnAllianceWriter.WriteAlliances(humans, ais, multiCmbIndexes, startingWaypoints, spawnIni);

        for (int multiIndex = 0; multiIndex < multiCmbIndexes.Count; multiIndex++)
        {
            int playerIndex = multiCmbIndexes[multiIndex];
            int startIndex = humans[playerIndex].StartIndex;
            if (startIndex > 0)
                spawnIni.SetIntValue("SpawnLocations", "Multi" + (multiIndex + 1), startIndex - 1);
        }

        for (int aiIndex = 0; aiIndex < ais.Count; aiIndex++)
        {
            int startIndex = ais[aiIndex].StartIndex;
            if (startIndex > 0)
            {
                int multiIndex = humans.Count + aiIndex + 1;
                spawnIni.SetIntValue("SpawnLocations", "Multi" + multiIndex, startIndex - 1);
            }
        }

        spawnIni.WriteIniFile();
        Logger.Log($"CnCNetMultiplayerSpawnWriter: tunnel {startInfo.Tunnel.Address}:{startInfo.Tunnel.Port}, gameId={startInfo.UniqueGameId}, localPort={localPort}");
    }

    private static List<LobbyPlayerSlot> BuildHumans(IReadOnlyList<IPlayerSlot> slots, IReadOnlyList<CnCNetGameRoomPlayer>? roomPlayers)
    {
        string localPlayerName;
        try { localPlayerName = EnvironmentServices.Resolve<IGameEnvironment>().PlayerName; }
        catch (InvalidOperationException)
        {
            // TODO(phase-A): inject IGameEnvironment — early test path
            localPlayerName = AppState.Environment.PlayerName;
        }

        if (roomPlayers != null)
        {
            return roomPlayers
                .Where(p => !p.IsAi && !string.IsNullOrWhiteSpace(p.Name))
                .Select(p => new LobbyPlayerSlot
                {
                    Name = p.Name,
                    SideIndex = p.SideId,
                    ColorIndex = p.ColorId,
                    StartIndex = p.StartingLocation,
                    TeamIndex = p.TeamId,
                    IsHumanLocal = p.Name.Equals(localPlayerName, StringComparison.OrdinalIgnoreCase),
                })
                .ToList();
        }

        return slots.Where(s => s.IsOccupied && !s.IsAi).Select(Clone).ToList();
    }

    private static List<LobbyPlayerSlot> BuildAis(IReadOnlyList<IPlayerSlot> slots, IReadOnlyList<CnCNetGameRoomPlayer>? roomPlayers)
    {
        if (roomPlayers != null)
        {
            return roomPlayers
                .Where(p => p.IsAi)
                .Select(p => new LobbyPlayerSlot
                {
                    Name = p.Name,
                    IsAi = true,
                    AiLevel = p.AiLevel,
                    SideIndex = p.SideId,
                    ColorIndex = p.ColorId,
                    StartIndex = p.StartingLocation,
                    TeamIndex = p.TeamId,
                })
                .ToList();
        }

        return slots.Where(s => s.IsOccupied && s.IsAi).Select(Clone).ToList();
    }

    /// <summary>把任意 <see cref="IPlayerSlot"/> 克隆为 <see cref="LobbyPlayerSlot"/>（spawn.ini 写入需要可变副本）。</summary>
    private static LobbyPlayerSlot Clone(IPlayerSlot slot)
    {
        if (slot is LobbyPlayerSlot concrete)
            return concrete.Clone();

        return new LobbyPlayerSlot
        {
            Name = slot.Name,
            SideIndex = slot.SideIndex,
            ColorIndex = slot.ColorIndex,
            TeamIndex = slot.TeamIndex,
            StartIndex = slot.StartIndex,
            AiLevel = slot.AiLevel,
            IsAi = slot.IsAi,
            IsHumanLocal = slot.IsHumanLocal,
        };
    }

    private static List<int> BuildMultiComboIndexes(
        IReadOnlyList<LobbyPlayerSlot> humans,
        IReadOnlyList<LobbyPlayerHouseResolver.ResolvedHouse> houses)
    {
        var mpColors = MultiplayerColorCatalog.Load().OrderBy(c => c.GameColorIndex).ToList();
        var indexes = new List<int>();

        foreach (MultiplayerColorCatalog.MultiplayerColorEntry color in mpColors)
        {
            for (int playerIndex = 0; playerIndex < humans.Count; playerIndex++)
            {
                if (houses[playerIndex].GameColorIndex == color.GameColorIndex)
                    indexes.Add(playerIndex);
            }
        }

        if (indexes.Count == 0)
        {
            for (int i = 0; i < humans.Count; i++)
                indexes.Add(i);
        }

        return indexes;
    }

    private static int GetHumanTeamCount(IReadOnlyList<LobbyPlayerSlot> humans)
    {
        int[] teamCounts = new int[4];
        int teamsWithTwo = 0;
        foreach (LobbyPlayerSlot human in humans)
        {
            if (human.TeamIndex <= 0)
                continue;

            int idx = human.TeamIndex - 1;
            if (idx < 0 || idx >= teamCounts.Length)
                continue;

            teamCounts[idx]++;
            if (teamCounts[idx] == 2)
                teamsWithTwo++;
        }

        return teamsWithTwo;
    }

    private static void ApplyForcedSpawnOptions(IniFile spawnIni)
    {
        string baseResourcesPath;
        try { baseResourcesPath = EnvironmentServices.Resolve<IGameEnvironment>().BaseResourcesPath; }
        catch (InvalidOperationException)
        {
            // TODO(phase-A): inject IGameEnvironment — early test path
            baseResourcesPath = AppState.Environment.BaseResourcesPath;
        }

        string gameOptionsPath = SafePath.CombineFilePath(baseResourcesPath, ClientConfiguration.GAME_OPTIONS);
        if (!File.Exists(gameOptionsPath))
            return;

        var gameOptionsIni = new IniFile(gameOptionsPath);
        List<string>? forcedKeys = gameOptionsIni.GetSectionKeys("ForcedSpawnIniOptions");
        if (forcedKeys == null)
            return;

        foreach (string key in forcedKeys)
        {
            spawnIni.SetStringValue("Settings", key,
                gameOptionsIni.GetStringValue("ForcedSpawnIniOptions", key, string.Empty));
        }
    }
}
