using ClientAvalonia.Configuration;
using ClientAvalonia.GlobalState;
using ClientCore;
using Rampastring.Tools;

namespace ClientAvalonia.Services;

/// <summary>Writes spawn.ini / spawnmap.ini for SP load (DX <c>GameLoadingWindow.BtnLaunch</c>).</summary>
public static class SinglePlayerLoadSpawnWriter
{
    public static void Write(string saveFileName)
    {
        string gamePath = AppState.Environment.GamePath;
        FileInfo spawnFile = SafePath.GetFile(gamePath, ProgramConstants.SPAWNER_SETTINGS);
        spawnFile.Delete();

        bool sidebarHack = false;
        try { sidebarHack = AppState.Configuration.SidebarHack; } catch { /* ignore */ }

        int gameSpeed = 1;
        try { gameSpeed = UserINISettings.Instance.GameSpeed.Value; } catch { /* ignore */ }

        using (var writer = new StreamWriter(spawnFile.FullName))
        {
            writer.WriteLine("; generated by ClientAvalonia");
            writer.WriteLine("[Settings]");
            writer.WriteLine("Scenario=" + ProgramConstants.SPAWNMAP_INI);
            writer.WriteLine("SaveGameName=" + saveFileName);
            writer.WriteLine("LoadSaveGame=Yes");
            writer.WriteLine("SidebarHack=" + sidebarHack);
            writer.WriteLine("Firestorm=No");
            writer.WriteLine("GameSpeed=" + gameSpeed);
            writer.WriteLine();
        }

        FileInfo mapFile = SafePath.GetFile(gamePath, ProgramConstants.SPAWNMAP_INI);
        mapFile.Delete();
        using (var writer = new StreamWriter(mapFile.FullName))
        {
            writer.WriteLine("[Map]");
            writer.WriteLine("Size=0,0,50,50");
            writer.WriteLine("LocalSize=0,0,50,50");
            writer.WriteLine();
        }

        Logger.Log("SinglePlayerLoadSpawnWriter: " + saveFileName);
    }
}

/// <summary>
/// MP load spawn: copy spawnSG.ini → spawn.ini, set SaveGameName / LoadSaveGame,
/// patch ports (DX <c>GameLoadingLobbyBase.LoadGame</c>).
/// </summary>
public static class MultiplayerLoadSpawnWriter
{
    /// <param name="savedGameIndex">Physical index into SVGM_NNN.NET (0-based ascending).</param>
    public static void Write(
        int savedGameIndex,
        bool isHost,
        int inGamePort,
        IReadOnlyDictionary<string, string>? otherIps = null)
    {
        string gamePath = AppState.Environment.GamePath;
        FileInfo sg = SafePath.GetFile(gamePath, ProgramConstants.SAVED_GAME_SPAWN_INI);
        if (!sg.Exists)
            throw new FileNotFoundException("spawnSG.ini not found", sg.FullName);

        FileInfo spawn = SafePath.GetFile(gamePath, ProgramConstants.SPAWNER_SETTINGS);
        spawn.Delete();
        File.Copy(sg.FullName, spawn.FullName);

        var ini = new IniFile(spawn.FullName);
        string saveName = string.Format("SVGM_{0}.NET", savedGameIndex.ToString("D3"));
        ini.SetStringValue("Settings", "SaveGameName", saveName);
        ini.SetBooleanValue("Settings", "LoadSaveGame", true);
        ini.SetIntValue("Settings", "Port", inGamePort);
        ini.SetBooleanValue("Settings", "Host", isHost);

        if (otherIps != null)
        {
            int i = 0;
            while (ini.SectionExists("Other" + i))
            {
                string name = ini.GetStringValue("Other" + i, "Name", string.Empty);
                if (otherIps.TryGetValue(name, out string? ip) && !string.IsNullOrWhiteSpace(ip))
                    ini.SetStringValue("Other" + i, "Ip", ip);
                ini.SetIntValue("Other" + i, "Port", inGamePort);
                i++;
            }
        }

        ini.WriteIniFile();

        FileInfo mapFile = SafePath.GetFile(gamePath, ProgramConstants.SPAWNMAP_INI);
        if (!mapFile.Exists)
        {
            using var writer = new StreamWriter(mapFile.FullName);
            writer.WriteLine("[Map]");
            writer.WriteLine("Size=0,0,50,50");
            writer.WriteLine("LocalSize=0,0,50,50");
            writer.WriteLine();
        }

        Logger.Log($"MultiplayerLoadSpawnWriter: {saveName}, host={isHost}, port={inGamePort}");
    }
}

public sealed class SinglePlayerLoadLaunchSession(string saveFileName) : IGameLaunchSession
{
    public string LaunchModeLabel => "SinglePlayerLoad";

    public void PrepareSpawnFiles()
        => SinglePlayerLoadSpawnWriter.Write(saveFileName);
}
