using ClientAvalonia.Domain;
using ClientAvalonia.Rendering;
using ClientCore;
using Rampastring.Tools;

namespace ClientAvalonia.Services;

/// <summary>Writes spawn.ini and spawnmap.ini for skirmish (aligned with GameLobbyBase.WriteSpawnIni / WriteMap).</summary>
public static class SkirmishSpawnWriter
{
    public static void Write(
        MapEntry map,
        GameModeEntry gameMode,
        LobbyPlayerState? players = null,
        UiNodeViewModel? lobbyRoot = null,
        int randomSeed = 0)
    {
        if (randomSeed == 0)
            randomSeed = Random.Shared.Next();

        WriteSpawnIni(map, gameMode, players, lobbyRoot, randomSeed);
        WriteSpawnMap(map, gameMode, lobbyRoot);
    }

    private static void WriteSpawnIni(
        MapEntry map,
        GameModeEntry gameMode,
        LobbyPlayerState? players,
        UiNodeViewModel? lobbyRoot,
        int randomSeed)
    {
        FileInfo spawnerSettingsFile = SafePath.GetFile(ProgramConstants.GamePath, ProgramConstants.SPAWNER_SETTINGS);
        spawnerSettingsFile.Delete();

        Logger.Log("SkirmishSpawnWriter: writing spawn.ini");

        var humans = GetOccupiedSlots(players, ai: false);
        var ais = GetOccupiedSlots(players, ai: true);
        if (humans.Count == 0)
        {
            humans.Add(new LobbyPlayerSlot
            {
                Name = ProgramConstants.PLAYERNAME,
                IsHumanLocal = true,
            });
        }

        if (ais.Count == 0)
        {
            ais.Add(new LobbyPlayerSlot
            {
                Name = ProgramConstants.AI_PLAYER_NAMES[0],
                IsAi = true,
                AiLevel = 0,
                SideIndex = 0,
                ColorIndex = 1,
            });
        }

        LobbyPlayerSlot localPlayer = humans.FirstOrDefault(s => s.IsHumanLocal) ?? humans[0];
        var allOccupied = new List<LobbyPlayerSlot>(humans.Count + ais.Count);
        allOccupied.AddRange(humans);
        allOccupied.AddRange(ais);
        IReadOnlyList<LobbyPlayerHouseResolver.ResolvedHouse> houses =
            LobbyPlayerHouseResolver.Resolve(allOccupied, randomSeed);

        int localHumanIndex = humans.FindIndex(h => h.IsHumanLocal || h.Name == ProgramConstants.PLAYERNAME);
        if (localHumanIndex < 0)
            localHumanIndex = 0;

        var spawnIni = new IniFile(spawnerSettingsFile.FullName) { Comment = "Generated by CnCNet Client" };
        var settings = new IniSection("Settings");

        LobbyPlayerHouseResolver.ResolvedHouse localHouse = houses[localHumanIndex];

        settings.SetStringValue("Name", ProgramConstants.PLAYERNAME);
        settings.SetStringValue("Scenario", ProgramConstants.SPAWNMAP_INI);
        settings.SetStringValue("UIGameMode", gameMode.UntranslatedUIName);
        settings.SetStringValue("UIMapName", map.UntranslatedName);

        if (map.IsOfficial)
            settings.SetStringValue("MapID", map.BaseFilePath);

        settings.SetIntValue("PlayerCount", humans.Count);
        settings.SetIntValue("Side", localHouse.InternalSideIndex);
        settings.SetBooleanValue("IsSpectator", localHouse.IsSpectator);
        settings.SetIntValue("Color", localHouse.GameColorIndex);
        settings.SetStringValue("CustomLoadScreen", LoadingScreenController.GetLoadScreenName(localHouse.InternalSideIndex.ToString()));
        settings.SetIntValue("AIPlayers", ais.Count);
        settings.SetIntValue("Seed", randomSeed);

        spawnIni.AddSection(settings);

        int otherId = 1;
        for (int humanIndex = 0; humanIndex < humans.Count; humanIndex++)
        {
            LobbyPlayerSlot human = humans[humanIndex];
            if (human.Name == ProgramConstants.PLAYERNAME)
                continue;

            LobbyPlayerHouseResolver.ResolvedHouse house = houses[humanIndex];
            string sectionName = "Other" + otherId;
            spawnIni.SetStringValue(sectionName, "Name", human.Name);
            spawnIni.SetIntValue(sectionName, "Side", house.InternalSideIndex);
            spawnIni.SetBooleanValue(sectionName, "IsSpectator", house.IsSpectator);
            spawnIni.SetIntValue(sectionName, "Color", house.GameColorIndex);
            otherId++;
        }

        for (int aiId = 0; aiId < ais.Count; aiId++)
        {
            LobbyPlayerHouseResolver.ResolvedHouse house = houses[humans.Count + aiId];
            string keyName = "Multi" + (aiId + 2);
            spawnIni.SetIntValue("HouseHandicaps", keyName, LobbyPlayerState.HouseHandicapFromAiLevel(ais[aiId].AiLevel));
            spawnIni.SetIntValue("HouseCountries", keyName, house.InternalSideIndex);
            spawnIni.SetIntValue("HouseColors", keyName, house.GameColorIndex);
        }

        SpawnIniApplier.ApplySpawnDefaults(spawnIni);
        SpawnIniApplier.ApplyLobbyControls(lobbyRoot, spawnIni);
        ApplyForcedSpawnOptions(spawnIni);
        ForcedSpawnCatalog.ApplyGameModeForcedSpawn(spawnIni, gameMode);
        ForcedSpawnCatalog.ApplyMapForcedSpawn(spawnIni, map, humans.Count, ais.Count);

        spawnIni.WriteIniFile();
    }

    private static List<LobbyPlayerSlot> GetOccupiedSlots(LobbyPlayerState? players, bool ai)
    {
        if (players == null)
            return [];

        return players.Slots.Where(s => s.IsOccupied && s.IsAi == ai).ToList();
    }

    public static void WriteSpawnMap(MapEntry map, GameModeEntry gameMode, UiNodeViewModel? lobbyRoot)
    {
        FileInfo spawnMapIniFile = SafePath.GetFile(ProgramConstants.GamePath, ProgramConstants.SPAWNMAP_INI);
        spawnMapIniFile.Delete();

        Logger.Log($"SkirmishSpawnWriter: writing spawnmap.ini from {map.CompleteFilePath}");

        IniFile mapIni = MapCodeHelper.LoadMapIni(map);

        var globalCodeIni = new IniFile(SafePath.CombineFilePath(ProgramConstants.GamePath, "INI", "Map Code", "GlobalCode.ini"));
        MapCodeHelper.ApplyMapCode(mapIni, MapCodeHelper.GetGameModeMapCodePath(gameMode), gameMode);
        MapCodeHelper.ApplyMapCode(mapIni, globalCodeIni);
        SpawnIniApplier.ApplyMapCodeControls(lobbyRoot, mapIni, gameMode);

        string mapIniFileName = Path.GetFileName(mapIni.FileName);
        mapIni.SetStringValue("Basic", "OriginalFilename", mapIniFileName);
        mapIni.MoveSectionToFirst("MultiplayerDialogSettings");

        mapIni.WriteIniFile(spawnMapIniFile.FullName);
    }

    private static void ApplyForcedSpawnOptions(IniFile spawnIni)
    {
        string gameOptionsPath = SafePath.CombineFilePath(ProgramConstants.GetBaseResourcePath(), ClientConfiguration.GAME_OPTIONS);
        if (!File.Exists(gameOptionsPath))
            return;

        var gameOptionsIni = new IniFile(gameOptionsPath);
        List<string>? forcedKeys = gameOptionsIni.GetSectionKeys("ForcedSpawnIniOptions");
        if (forcedKeys == null)
            return;

        foreach (string key in forcedKeys)
        {
            spawnIni.SetStringValue("Settings", key,
                gameOptionsIni.GetStringValue("ForcedSpawnIniOptions", key, string.Empty));
        }
    }
}
