using ClientAvalonia.Domain;
using ClientAvalonia.Rendering;
using ClientAvalonia.Session;
using ClientCore;
using Rampastring.Tools;
using ClientAvalonia.GlobalState;

namespace ClientAvalonia.Services;

/// <summary>Writes spawn.ini and spawnmap.ini for skirmish (aligned with GameLobbyBase.WriteSpawnIni / WriteMap).</summary>
public static class SkirmishSpawnWriter
{
    /// <summary>
    /// Phase 3 P3-2：Session-aware 主入口——吃 <see cref="IReadOnlyList{IPlayerSlot}"/> + sideCount，
    /// 不再依赖 <c>LobbyPlayerState</c>。
    /// </summary>
    /// <param name="map">选中地图。</param>
    /// <param name="gameMode">选中游戏模式。</param>
    /// <param name="slots">槽位列表（通常是 <see cref="IGameSession.PlayerSlots"/>）。</param>
    /// <param name="sideCount">可选阵营数（控制 random side 上界；<=0 时按 occupied slot.SideIndex 透传）。</param>
    /// <param name="lobbyRoot">可选 lobby UI 树（写 spawnmap 需要）。</param>
    /// <param name="randomSeed">可复现随机种子；0 表示自动生成。</param>
    public static void Write(
        MapEntry map,
        GameModeEntry gameMode,
        IReadOnlyList<IPlayerSlot> slots,
        int sideCount,
        UiNodeViewModel? lobbyRoot = null,
        int randomSeed = 0)
    {
        if (randomSeed == 0)
            randomSeed = Random.Shared.Next();

        WriteSpawnIni(map, gameMode, slots, sideCount, lobbyRoot, randomSeed);
        WriteSpawnMap(map, gameMode, lobbyRoot);
    }

    private static void WriteSpawnIni(
        MapEntry map,
        GameModeEntry gameMode,
        IReadOnlyList<IPlayerSlot> slots,
        int sideCount,
        UiNodeViewModel? lobbyRoot,
        int randomSeed)
    {
        FileInfo spawnerSettingsFile = SafePath.GetFile(AppState.Environment.GamePath, ProgramConstants.SPAWNER_SETTINGS);
        spawnerSettingsFile.Delete();

        Logger.Log("Writing spawn.ini");

        var humans = slots.Where(s => s.IsOccupied && !s.IsAi).Select(Clone).ToList();
        var ais = slots.Where(s => s.IsOccupied && s.IsAi).Select(Clone).ToList();
        if (humans.Count == 0)
        {
            humans.Add(new LobbyPlayerSlot
            {
                Name = AppState.Environment.PlayerName,
                IsHumanLocal = true,
            });
        }

        if (ais.Count == 0)
        {
            ais.Add(new LobbyPlayerSlot
            {
                Name = AppState.Environment.AiPlayerNames[0],
                IsAi = true,
                AiLevel = 0,
                SideIndex = 0,
                ColorIndex = 1,
            });
        }

        LobbyPlayerSlot localPlayer = humans.FirstOrDefault(s => s.IsHumanLocal) ?? humans[0];
        var allOccupied = new List<LobbyPlayerSlot>(humans.Count + ais.Count);
        allOccupied.AddRange(humans);
        allOccupied.AddRange(ais);
        IReadOnlyList<LobbyPlayerHouseResolver.ResolvedHouse> houses =
            LobbyPlayerHouseResolver.Resolve((IReadOnlyList<IPlayerSlot>)allOccupied, randomSeed);

        int localHumanIndex = humans.FindIndex(h => h.IsHumanLocal || h.Name == AppState.Environment.PlayerName);
        if (localHumanIndex < 0)
            localHumanIndex = 0;

        var spawnIni = new IniFile(spawnerSettingsFile.FullName) { Comment = "Generated by CnCNet Client" };
        var settings = new IniSection("Settings");

        LobbyPlayerHouseResolver.ResolvedHouse localHouse = houses[localHumanIndex];

        settings.SetStringValue("Name", AppState.Environment.PlayerName);
        settings.SetStringValue("Scenario", ProgramConstants.SPAWNMAP_INI);
        settings.SetStringValue("UIGameMode", gameMode.UntranslatedUIName);
        settings.SetStringValue("UIMapName", map.UntranslatedName);

        if (map.IsOfficial)
            settings.SetStringValue("MapID", map.BaseFilePath);

        settings.SetIntValue("PlayerCount", humans.Count);
        settings.SetIntValue("Side", localHouse.InternalSideIndex);
        settings.SetBooleanValue("IsSpectator", localHouse.IsSpectator);
        settings.SetIntValue("Color", localHouse.GameColorIndex);
        settings.SetStringValue("CustomLoadScreen", LoadingScreenController.GetLoadScreenName(localHouse.InternalSideIndex.ToString()));
        settings.SetIntValue("AIPlayers", ais.Count);
        settings.SetIntValue("Seed", randomSeed);

        spawnIni.AddSection(settings);

        int otherId = 1;
        for (int humanIndex = 0; humanIndex < humans.Count; humanIndex++)
        {
            LobbyPlayerSlot human = humans[humanIndex];
            if (human.Name == AppState.Environment.PlayerName)
                continue;

            LobbyPlayerHouseResolver.ResolvedHouse house = houses[humanIndex];
            string sectionName = "Other" + otherId;
            spawnIni.SetStringValue(sectionName, "Name", human.Name);
            spawnIni.SetIntValue(sectionName, "Side", house.InternalSideIndex);
            spawnIni.SetBooleanValue(sectionName, "IsSpectator", house.IsSpectator);
            spawnIni.SetIntValue(sectionName, "Color", house.GameColorIndex);
            otherId++;
        }

        for (int aiId = 0; aiId < ais.Count; aiId++)
        {
            LobbyPlayerHouseResolver.ResolvedHouse house = houses[humans.Count + aiId];
            string keyName = "Multi" + (aiId + 2);
            spawnIni.SetIntValue("HouseHandicaps", keyName, LobbyPlayerHouseResolver.HouseHandicapFromAiLevel(ais[aiId].AiLevel));
            spawnIni.SetIntValue("HouseCountries", keyName, house.InternalSideIndex);
            spawnIni.SetIntValue("HouseColors", keyName, house.GameColorIndex);
        }

        SpawnIniApplier.ApplySpawnDefaults(spawnIni);
        SpawnIniApplier.ApplyLobbyControls(lobbyRoot, spawnIni);
        ApplyForcedSpawnOptions(spawnIni);
        ForcedSpawnCatalog.ApplyGameModeForcedSpawn(spawnIni, gameMode);
        ForcedSpawnCatalog.ApplyMapForcedSpawn(spawnIni, map, humans.Count, ais.Count);

        spawnIni.WriteIniFile();
    }

    /// <summary>把任意 <see cref="IPlayerSlot"/> 克隆为 <see cref="LobbyPlayerSlot"/>（spawn.ini 写入需要具体类型持有可变字段）。</summary>
    private static LobbyPlayerSlot Clone(IPlayerSlot slot)
    {
        if (slot is LobbyPlayerSlot concrete)
            return concrete.Clone();

        return new LobbyPlayerSlot
        {
            Name = slot.Name,
            SideIndex = slot.SideIndex,
            ColorIndex = slot.ColorIndex,
            TeamIndex = slot.TeamIndex,
            StartIndex = slot.StartIndex,
            AiLevel = slot.AiLevel,
            IsAi = slot.IsAi,
            IsHumanLocal = slot.IsHumanLocal,
        };
    }

    public static void WriteSpawnMap(MapEntry map, GameModeEntry gameMode, UiNodeViewModel? lobbyRoot)
    {
        FileInfo spawnMapIniFile = SafePath.GetFile(AppState.Environment.GamePath, ProgramConstants.SPAWNMAP_INI);
        spawnMapIniFile.Delete();

        Logger.Log("Writing map.");

        IniFile mapIni = MapCodeHelper.LoadMapIni(map);

        var globalCodeIni = new IniFile(SafePath.CombineFilePath(AppState.Environment.GamePath, "INI", "Map Code", "GlobalCode.ini"));
        MapCodeHelper.ApplyMapCode(mapIni, MapCodeHelper.GetGameModeMapCodePath(gameMode), gameMode);
        MapCodeHelper.ApplyMapCode(mapIni, globalCodeIni);
        SpawnIniApplier.ApplyMapCodeControls(lobbyRoot, mapIni, gameMode);

        string mapIniFileName = Path.GetFileName(mapIni.FileName);
        mapIni.SetStringValue("Basic", "OriginalFilename", mapIniFileName);
        mapIni.MoveSectionToFirst("MultiplayerDialogSettings");

        mapIni.WriteIniFile(spawnMapIniFile.FullName);
    }

    private static void ApplyForcedSpawnOptions(IniFile spawnIni)
    {
        string gameOptionsPath = SafePath.CombineFilePath(AppState.Environment.BaseResourcesPath, ClientConfiguration.GAME_OPTIONS);
        if (!File.Exists(gameOptionsPath))
            return;

        var gameOptionsIni = new IniFile(gameOptionsPath);
        List<string>? forcedKeys = gameOptionsIni.GetSectionKeys("ForcedSpawnIniOptions");
        if (forcedKeys == null)
            return;

        foreach (string key in forcedKeys)
        {
            spawnIni.SetStringValue("Settings", key,
                gameOptionsIni.GetStringValue("ForcedSpawnIniOptions", key, string.Empty));
        }
    }
}
